### ISSUE TITLE
Boost testcase fails with llvm and gcc

### ISSUE THREAD

**Issue by kamleshbhalui** [boostorg/lambda#16]
One test in  lambda test case [result_of_tests.cpp] is failing  in llvm and gcc compiler.

[https://github.com/boostorg/lambda/blob/develop/test/result_of_tests.cpp#L303]

when compiled with O2 optimization.
Testcase is trying to return an stack allocated memory reference to caller. Which is actually an undefine behavior.

So when we do store to that stack allocated memory before returning from function,
 one optimization called Dead Store Elimination pass deletes the store to stack allocated memory in exit block ,Thinking that all these store is dead when we go out of this function scope.
And It results in above testcase failure.
Do we need to disable this test or their any other way around?

**Comment by pdimov** [comment]
Fixed by #17.
