### ISSUE TITLE
List of non BOOST-prefixed macros

### ISSUE THREAD

**Issue by ned14** [boostorg/lambda#18]
The following macros are missing a BOOST_ prefix, which is against Boost library guidelines. The corresponding Phoenix open issue is at https://github.com/boostorg/phoenix/issues/90

```
./boost/lambda/closures.hpp:#ifndef PHOENIX_CLOSURES_HPP
./boost/lambda/closures.hpp:#define PHOENIX_CLOSURES_HPP
```

**Comment by glenfe** [comment]
Fixed in 8de6d9cb9fe9d486a5fd74fd9dd3dc805abab937.
